version: "3.8"
services:
  app:
    build: .
    container_name: fastapi_plantalert
    restart: always
    env_file:
      - ".env"
    ports:
      - "8000:80"  # Adjust port as needed
    volumes:
      - .:/app # Mount the current directory into the container for development
    networks:
      mariadb-influxdb-api-rocnikovka:
        ipv4_address: 172.19.0.3

networks:
  mariadb-influxdb-api-rocnikovka:
    external: true